-- =============================================================================
-- LedgerLens Seed Data — Development Only
-- =============================================================================
-- Minimal seed data for development and testing.
-- Full synthetic dataset is generated by: npm run generate-data
-- =============================================================================

-- Clean slate (for re-seeding during development)
TRUNCATE TABLE audit_logs CASCADE;
TRUNCATE TABLE exceptions CASCADE;
TRUNCATE TABLE reconciliation_results CASCADE;
TRUNCATE TABLE reconciliation_runs CASCADE;
TRUNCATE TABLE bank_transactions CASCADE;
TRUNCATE TABLE settlements CASCADE;
TRUNCATE TABLE payments CASCADE;

-- =============================================================================
-- SEED: A tiny representative dataset for smoke testing
-- 5 payments with different scenarios
-- =============================================================================

-- ── Payments ──────────────────────────────────────────────────────────────────
INSERT INTO payments (id, merchant_id, payment_id, customer_id, amount, currency, status, payment_method, payment_date, source) VALUES
  ('00000000-0000-0000-0000-000000000001', 'demo_merchant', 'pay_seed_001', 'cust_001', 10000.00, 'INR', 'captured', 'upi',        '2024-01-15 10:00:00+05:30', 'seed'),
  ('00000000-0000-0000-0000-000000000002', 'demo_merchant', 'pay_seed_002', 'cust_002',  5000.00, 'INR', 'captured', 'card',       '2024-01-15 11:00:00+05:30', 'seed'),
  ('00000000-0000-0000-0000-000000000003', 'demo_merchant', 'pay_seed_003', 'cust_003', 25000.00, 'INR', 'captured', 'netbanking', '2024-01-15 12:00:00+05:30', 'seed'),
  ('00000000-0000-0000-0000-000000000004', 'demo_merchant', 'pay_seed_004', 'cust_004',  1500.00, 'INR', 'captured', 'upi',        '2024-01-15 13:00:00+05:30', 'seed'),
  ('00000000-0000-0000-0000-000000000005', 'demo_merchant', 'pay_seed_005', 'cust_005',  8000.00, 'INR', 'captured', 'wallet',     '2024-01-15 14:00:00+05:30', 'seed');

-- ── Settlements ────────────────────────────────────────────────────────────────
-- Standard fee rate: 2% + 18% GST on fees
-- pay_seed_001: exact match (₹10,000 → fee ₹200 → gst ₹36 → net ₹9,764)
-- pay_seed_002: exact match (₹5,000  → fee ₹100 → gst ₹18 → net ₹4,882)
-- pay_seed_003: amount mismatch scenario
-- pay_seed_004: no settlement (MISSING_SETTLEMENT scenario)
-- pay_seed_005: exact match
INSERT INTO settlements (id, merchant_id, settlement_id, amount, fees, tax, net_amount, utr, settlement_date, status, source) VALUES
  ('00000000-0000-0000-1000-000000000001', 'demo_merchant', 'setl_seed_001', 10000.00, 200.00, 36.00, 9764.00, 'UTR2024011500001', '2024-01-16 09:00:00+05:30', 'processed', 'seed'),
  ('00000000-0000-0000-1000-000000000002', 'demo_merchant', 'setl_seed_002',  5000.00, 100.00, 18.00, 4882.00, 'UTR2024011500002', '2024-01-16 09:00:00+05:30', 'processed', 'seed'),
  ('00000000-0000-0000-1000-000000000003', 'demo_merchant', 'setl_seed_003', 25000.00, 500.00, 90.00, 24410.00, 'UTR2024011500003', '2024-01-16 09:00:00+05:30', 'processed', 'seed'),
  ('00000000-0000-0000-1000-000000000005', 'demo_merchant', 'setl_seed_005',  8000.00, 160.00, 28.80, 7811.20, 'UTR2024011500005', '2024-01-16 09:00:00+05:30', 'processed', 'seed');

-- ── Bank Transactions ──────────────────────────────────────────────────────────
-- pay_seed_001: exact match
-- pay_seed_002: exact match
-- pay_seed_003: amount mismatch (bank got ₹24,000 instead of ₹24,410)
-- pay_seed_004: no bank entry (MISSING_BANK scenario)
-- pay_seed_005: exact match
INSERT INTO bank_transactions (id, merchant_id, bank_reference, utr, amount, transaction_type, transaction_date, description, source) VALUES
  ('00000000-0000-0000-2000-000000000001', 'demo_merchant', 'BANK2024011500001', 'UTR2024011500001',  9764.00, 'credit', '2024-01-16 10:00:00+05:30', 'NEFT from Razorpay - pay_seed_001', 'seed'),
  ('00000000-0000-0000-2000-000000000002', 'demo_merchant', 'BANK2024011500002', 'UTR2024011500002',  4882.00, 'credit', '2024-01-16 10:00:00+05:30', 'NEFT from Razorpay - pay_seed_002', 'seed'),
  ('00000000-0000-0000-2000-000000000003', 'demo_merchant', 'BANK2024011500003', 'UTR2024011500003', 24000.00, 'credit', '2024-01-16 10:00:00+05:30', 'NEFT from Razorpay - pay_seed_003', 'seed'),
  ('00000000-0000-0000-2000-000000000005', 'demo_merchant', 'BANK2024011500005', 'UTR2024011500005',  7811.20, 'credit', '2024-01-16 10:00:00+05:30', 'NEFT from Razorpay - pay_seed_005', 'seed');

-- ── Reconciliation Run ─────────────────────────────────────────────────────────
INSERT INTO reconciliation_runs (id, merchant_id, started_at, completed_at, total_records, matched_records, ai_resolved_records, review_records, unresolved_records, match_rate, resolution_rate, processing_time_ms, status) VALUES
  ('00000000-0000-0000-3000-000000000001', 'demo_merchant', '2024-01-16 11:00:00+05:30', '2024-01-16 11:00:05+05:30', 5, 3, 1, 1, 0, 0.6000, 0.8000, 5200, 'completed');

-- ── Audit Log ─────────────────────────────────────────────────────────────────
INSERT INTO audit_logs (user_id, action, entity_type, entity_id, reason) VALUES
  (NULL, 'IMPORT_COMPLETED',          'import', 'seed-import-001', 'Seed data loaded for development'),
  (NULL, 'RECONCILIATION_COMPLETED',  'run',    '00000000-0000-0000-3000-000000000001', 'Seed reconciliation run completed');
